### PR TITLE
Replace `force_reenumeration` with `force_reset`

### PR DESCRIPTION
**Pull request by hannobraun**
This removes the `force_reenumeration` method and replaces it with an
implementation of `usb_device::bus::UsbBus::force_reset`. I'm not at all
sure if this is the right thing to do, but here's my reasoning why I
think it might be:

- Both methods seem to have the same purpose.
- I can't see a reason _not_ to implement `force_reset`
  I might be missing some vital context, of course, but at least I can
  say that this method seems to work for me (USB device is recognized by
  the host PC right after flashing the program; it isn't if I don't call
  the method).
- I can't find a way to actually call `force_reenumeration`.
  It's a method on `stm32_usbd::bus::UsbBus`, but the constructor of
  that type only provides a `UsbBusAllocator`. I couldn't figure out how
  to get a `UsbBus` instance to call that method on.

My best guess is that something changed in `usb-device`, `stm32-usbd`
was updated, and that update caused a situation that no longer makes
sense. If that's true, then the fix in this commit is probably correct.

If this is wrong and I'm missing something (which is totally possible!),
I'd appreciate some guidance on how to call `force_reenumeration`.

### CODE REVIEW

**Comment by Disasm** [comment]
This `force_reset` was a hack for STM32F103, specifically for the BluePill **board**. F103 peripheral does not have any means for disconnecting from the bus, so you need to use board-specific hacks instead. Unfortunately, it's difficult to implement them now with more proper ownership handling. That's why `force_reset` can return `UsbError::Unsupported` for devices that do not support disconnect natively.

Aside of this, I'd like to remove `force_reset` completely: https://github.com/mvirkkunen/usb-device/pull/20. The reason is simple: why use method that is supported "sometimes" when you can use device-specific method instead (`force_reenumeration`, for example) which will present only on those devices where this disconnect functionality is actually supported. This method is accessible through the [`bus()` method](https://github.com/mvirkkunen/usb-device/commit/a6f88beb8641e94f16fdf9ae5a1bce9c69f4cf92) on UsbDevice.

**Comment by hannobraun** [comment]
Thank you, @Disasm, that makes sense.

> This method is accessible through the [`bus()` method](https://github.com/mvirkkunen/usb-device/commit/a6f88beb8641e94f16fdf9ae5a1bce9c69f4cf92) on UsbDevice.

Ah, and that commit not released on crates.io yet, which is why I didn't find it :-)

**Comment by Disasm** [comment]
@hannobraun `usb-device` 0.2.3 is out

**Comment by hannobraun** [comment]
@Disasm Thanks for the heads-up!

**Pull request closed without merging**
